USE [master]
GO
/****** Object:  Database [BankProjectDb]    Script Date: 12.02.2026 15:54:04 ******/
-- NOTE:
-- The original script contained physical file paths (FILENAME = ...).
-- These were removed to make the script portable and runnable
-- on any SQL Server instance without machine-specific dependencies.

IF DB_ID(N'BankProjectDb') IS NOT NULL
BEGIN
    ALTER DATABASE [BankProjectDb] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [BankProjectDb];
END
GO

CREATE DATABASE [BankProjectDb];
GO

ALTER DATABASE [BankProjectDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BankProjectDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BankProjectDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BankProjectDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BankProjectDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BankProjectDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BankProjectDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [BankProjectDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BankProjectDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BankProjectDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BankProjectDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BankProjectDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BankProjectDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BankProjectDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BankProjectDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BankProjectDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BankProjectDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BankProjectDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BankProjectDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BankProjectDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BankProjectDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BankProjectDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BankProjectDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BankProjectDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BankProjectDb] SET RECOVERY FULL 
GO
ALTER DATABASE [BankProjectDb] SET  MULTI_USER 
GO
ALTER DATABASE [BankProjectDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BankProjectDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BankProjectDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BankProjectDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BankProjectDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BankProjectDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BankProjectDb', N'ON'
GO
ALTER DATABASE [BankProjectDb] SET QUERY_STORE = ON
GO
/****** This Project Created By Emirhan Efe Gozpinar, Mustafa Hayrullah Yıldız and Seyhmus Elik ******/
ALTER DATABASE [BankProjectDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BankProjectDb]